import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'
import { ADMIN, OWNER, STAFF } from '@/constants/roles.constant'

const navigationConfig: NavigationTree[] = [
    // {
    //     key: 'home',
    //     path: '/home',
    //     title: 'Home',
    //     translateKey: 'nav.home',
    //     icon: 'home',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    {
        key: 'dashboard',
        path: '/owner/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [OWNER],
        subMenu: [],
    },

    {
        key: 'dishManagement',
        path: '',
        title: 'Menu(Dish)',
        icon: 'singleMenu', //'Group collapse menu',
        translateKey: 'nav.orderManagement',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER, STAFF],
        subMenu: [
            {
                key: 'menuDish.item1',
                path: '/restaurants/:restaurantId/dishes',
                title: 'Menu(dish) List',
                translateKey: 'dishManagement.collapse.item1',
                icon: 'list',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'menuDish.item2',
                path: '/dishes/create/:restaurantId',
                title: 'Menu(dish) Create',
                translateKey: 'dishManagement.collapse.item2',
                icon: 'create',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'staffManagement',
        path: '',
        title: 'Staff',
        icon: 'collapseMenu', //'Group collapse menu',
        translateKey: 'nav.staffManagement',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER],
        subMenu: [
            {
                key: 'staff.item1',
                path: '/restaurants/:restaurantId/staffs',
                title: 'Staff List',
                translateKey: 'staffManagement.collapse.item1',
                icon: 'list',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            // {
            //     key: 'staff.item2',
            //     path: '/restaurants/:restaurantId/staff/:staffId',
            //     title: 'Staff Detail',
            //     translateKey: 'staffManagement.collapse.item2',
            //     icon: 'detail',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
            {
                key: 'staff.item3',
                path: '/restaurants/:restaurantId/staff/create',
                title: 'Staff Create',
                translateKey: 'dishManagement.collapse.item4',
                icon: 'create',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'tableManagement',
        path: '',
        title: 'Table',
        icon: 'collapseMenu',
        translateKey: 'table.management',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER, STAFF],
        subMenu: [
            {
                key: 'table.item1',
                path: '/restaurants/:restaurantId/tables',
                title: 'Table List',
                translateKey: 'tableManagement.collapse.item1',
                icon: 'list',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'table.item2',
                path: '/restaurants/:restaurantId/tables/create',
                title: 'Table Create',
                translateKey: 'tableManagement.collapse.item2',
                icon: 'create',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'blogManagement',
        path: '',
        title: 'Blog',
        icon: 'collapseMenu',
        translateKey: 'cuisine.management',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER, STAFF],
        subMenu: [
            {
                key: 'blog.item1',
                path: '/blogs',
                title: 'Blog List',
                translateKey: 'blogManagement.collapse.item1',
                icon: 'list',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'blog.item2',
                path: '/blogs/:id',
                title: 'Blog Create',
                translateKey: 'blogManagement.collapse.item2',
                icon: 'create',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'cuisineManagement',
        path: '',
        title: 'Cuisine',
        icon: 'collapseMenu',
        translateKey: 'cuisine.management',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'cuisine.item1',
                path: '/cuisines',
                title: 'Cuisine List',
                translateKey: 'cuisineManagement.collapse.item1',
                icon: 'list',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'cuisine.item2',
                path: '/cuisines/:id',
                title: 'Cuisine Create',
                translateKey: 'cuisineManagement.collapse.item2',
                icon: 'create',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'bannerManagement',
        path: '',
        title: 'Banner',
        icon: 'collapseMenu',
        translateKey: 'cuisine.management',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'banner.item1',
                path: '/banners',
                title: 'Banner List',
                translateKey: 'bannerManagement.collapse.item1',
                icon: 'list',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'banner.item2',
                path: '/banners/:id',
                title: 'Banner Create',
                translateKey: 'bannerManagement.collapse.item2',
                icon: 'create',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'user.list',
        path: '/users',
        title: 'Users',
        translateKey: 'user.list',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'owner.list',
        path: '/owners',
        title: 'Owners',
        translateKey: 'owners',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    // {
    //     key: 'orderManagement',
    //     path: '',
    //     title: 'Order Operations',
    //     icon: 'collapseMenu',
    //     translateKey: 'nav.orderManagement',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'orderManagement.item1',
    //             path: '/restaurants/:restaurantId/orders',
    //             title: 'Order List',
    //             translateKey: 'orderManagement.collapse.item1',
    //             icon: 'list',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [OWNER, STAFF],
    //             subMenu: [],
    //         },
    //     ],
    // },
    // {
    //     key: 'reservationManagement',
    //     path: '',
    //     title: 'Reservation',
    //     icon: 'Group collapse menu',
    //     translateKey: 'nav.orderManagement',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'menuDish.item1',
    //             path: '/reservations/:restaurantId/reservations',
    //             title: 'Reservation List',
    //             translateKey: 'reservationManagement.collapse.item1',
    //             icon: 'list',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },

    // {
    //     key: 'restaurantManagement',
    //     path: '',
    //     title: 'Restaurant Operations',
    //     translateKey: 'nav.restaurantOps',
    //     icon: 'restaurant',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [OWNER, ADMIN, STAFF],
    //     subMenu: [
    //         {
    //             key: 'orders',
    //             path: '/owner/dashboard', // Redirects to selector dashboard if no specific context active
    //             title: 'Orders Management',
    //             translateKey: 'nav.orders',
    //             icon: 'order',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [OWNER, ADMIN, STAFF],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'dishes',
    //             path: '/owner/dashboard',
    //             title: 'Menu Items / Dishes',
    //             translateKey: 'nav.dishes',
    //             icon: 'dish',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [OWNER, ADMIN, STAFF],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'reservations',
    //             path: '/owner/dashboard',
    //             title: 'Reservations',
    //             translateKey: 'nav.reservations',
    //             icon: 'calendar',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [OWNER, ADMIN, STAFF],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'staff',
    //             path: '/owner/dashboard',
    //             title: 'Staff Administration',
    //             translateKey: 'nav.staff',
    //             icon: 'users',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [OWNER, ADMIN],
    //             subMenu: [],
    //         },
    //     ],
    // },
    /** Example purpose only, please remove */
    // {
    //     key: 'singleMenuItem',
    //     path: '/single-menu-view',
    //     title: 'Single menu item',
    //     translateKey: 'nav.singleMenuItem',
    //     icon: 'singleMenu',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    // {
    //     key: 'collapseMenu',
    //     path: '',
    //     title: 'Restaurants',
    //     translateKey: 'nav.collapseMenu.collapseMenu',
    //     icon: 'collapseMenu',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'collapseMenu.item1',
    //             path: '/collapse-menu-item-view-1',
    //             title: 'Collapse menu item 1',
    //             translateKey: 'nav.collapseMenu.item1',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'collapseMenu.item2',
    //             path: '/collapse-menu-item-view-2',
    //             title: 'Collapse menu item 2',
    //             translateKey: 'nav.collapseMenu.item2',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },
    {
        key: 'ordersAndReservations',
        path: '',
        title: 'Orders & Reservations',
        translateKey: 'nav.groupMenu.groupMenu',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [OWNER, STAFF],
        subMenu: [
            {
                key: 'orderManagement.item1',
                path: '/restaurants/:restaurantId/orders',
                title: 'Order List',
                translateKey: 'orderManagement.collapse.item1',
                icon: 'groupSingleMenu', //'list',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER, STAFF],
                subMenu: [],
            },
            {
                key: 'reservationManagement.item1',
                path: '/restaurants/:restaurantId/reservations',
                title: 'Reservation List',
                translateKey: 'reservationManagement.collapse.item1',
                icon: 'groupCollapseMenu', //'list',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    // {
    //     key: 'groupMenu',
    //     path: '',
    //     title: 'Group Menu',
    //     translateKey: 'nav.groupMenu.groupMenu',
    //     icon: 'groupMenu',
    //     type: NAV_ITEM_TYPE_TITLE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'groupMenu.single',
    //             path: '/group-single-menu-item-view',
    //             title: 'Group single menu item',
    //             translateKey: 'nav.groupMenu.single',
    //             icon: 'groupSingleMenu',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'groupMenu.collapse',
    //             path: '',
    //             title: 'Group collapse menu',
    //             translateKey: 'nav.groupMenu.collapse.collapse',
    //             icon: 'groupCollapseMenu',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [],
    //             subMenu: [
    //                 {
    //                     key: 'groupMenu.collapse.item1',
    //                     path: '/group-collapse-menu-item-view-1',
    //                     title: 'Menu item 1',
    //                     translateKey: 'nav.groupMenu.collapse.item1',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'groupMenu.collapse.item2',
    //                     path: '/group-collapse-menu-item-view-2',
    //                     title: 'Menu item 2',
    //                     translateKey: 'nav.groupMenu.collapse.item2',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //             ],
    //         },
    //     ],
    // },
]

export default navigationConfig
