import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'
import { ADMIN, OWNER, STAFF } from '@/constants/roles.constant'

const navigationConfig: NavigationTree[] = [
    // {
    //     key: 'home',
    //     path: '/home',
    //     title: 'Home',
    //     translateKey: 'nav.home',
    //     icon: 'home',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    {
        key: 'dashboard',
        path: '/owner/dashboard',
        title: 'Main Dashboard',
        translateKey: 'nav.dashboard.main',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [OWNER],
        subMenu: [],
    },
    {
        key: 'restaurantProfile',
        path: '',
        title: 'Restaurant Profile',
        translateKey: 'nav.restaurantProfile.restaurantProfile',
        icon: 'profile',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER],
        subMenu: [
            {
                key: 'restaurant.profile',
                path: '/restaurant/restaurant-profile/:restaurantId',
                title: 'Profile View',
                translateKey: 'nav.restaurantProfile.view',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
            {
                key: 'restaurant.eda-dashboard',
                path: '/restaurants/:restaurantId/eda-dashboard',
                title: 'Restaurant Dashboard',
                translateKey: 'nav.dashboard.eda',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
            // {
            //     key: 'restaurantProfile.create',
            //     path: '/restaurant/create-restaurant-profile/:restaurantId',
            //     title: 'Create Profile',
            //     translateKey: 'nav.restaurantProfile.create',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
        ],
    },
    {
        key: 'restaurantManagement',
        path: '',
        title: 'Restaurant Management',
        translateKey: 'nav.restaurantManagement',
        icon: 'menu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER, STAFF],
        subMenu: [
            {
                key: 'dishManagement',
                path: '/restaurants/:restaurantId/dishes',
                title: 'Menu(Dish)',
                icon: 'menu', //'Group collapse menu',
                translateKey: 'nav.orderManagement',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER, STAFF],
                subMenu: [],
            },
            {
                key: 'staffManagement',
                path: '/restaurants/:restaurantId/staffs',
                title: 'Staffs',
                icon: 'staffs', //'Group collapse menu',
                translateKey: 'nav.staffManagement',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER],
                subMenu: [],
            },
            {
                key: 'tableManagement',
                path: '/restaurants/:restaurantId/tables',
                title: 'Tables',
                icon: 'table',
                translateKey: 'table.management',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER, STAFF],
                subMenu: [],
            },
            {
                key: 'blogManagement',
                path: '/restaurants/:restaurantId/blogs',
                title: 'Blog',
                icon: 'blogs',
                translateKey: 'cuisine.management',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER, STAFF],
                subMenu: [],
            },
        ],
    },
    {
        key: 'owner.list',
        path: '/owners',
        title: 'Owners',
        translateKey: 'owners',
        icon: 'owners',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'bannerManagement',
        path: '/banners',
        title: 'Banners',
        icon: 'banner',
        translateKey: 'cuisine.management',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'banner.list',
                path: '/banners',
                title: 'Banner List',
                translateKey: 'bannerManagement.collapse.item1',
                icon: 'list',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'banner.create',
                path: '/banners/create',
                title: 'Banner Create',
                translateKey: 'bannerManagement.collapse.item2',
                icon: 'create',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'cuisineManagement',
        path: '/cuisines',
        title: 'Cuisine',
        icon: 'cuisine',
        translateKey: 'cuisine.management',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'cuisine.list',
                path: '/cuisines',
                title: 'Cuisine List',
                translateKey: 'cuisineManagement.collapse.item1',
                icon: 'list',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'cuisine.detail',
                path: '/cuisines/:id',
                title: 'Cuisine Create',
                translateKey: 'cuisineManagement.collapse.item2',
                icon: 'create',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'commissionManagement',
        path: '/commissions',
        title: 'Commissions',
        icon: 'commission',
        translateKey: 'commission.management',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'commission.list',
                path: '/commissions',
                title: 'Commission List',
                translateKey: 'commissionManagement.collapse.item1',
                icon: 'list',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'user.list',
        path: '/users',
        title: 'Users',
        translateKey: 'user.list',
        icon: 'users',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'appVersionManagement',
        path: '/app-versions',
        title: 'App Versions',
        icon: 'appVersion',
        translateKey: 'cuisine.management',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'appVersion.list',
                path: '/app-versions',
                title: 'App Version List',
                translateKey: 'appVersionManagement.collapse.item1',
                icon: 'list',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appVersion.create',
                path: '/app-versions/create',
                title: 'App Version Create',
                translateKey: 'appVersionManagement.collapse.item2',
                icon: 'create',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    // {
    //     key: 'orderManagement',
    //     path: '',
    //     title: 'Order Operations',
    //     icon: 'collapseMenu',
    //     translateKey: 'nav.orderManagement',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'orderManagement.item1',
    //             path: '/restaurants/:restaurantId/orders',
    //             title: 'Order List',
    //             translateKey: 'orderManagement.collapse.item1',
    //             icon: 'list',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [OWNER, STAFF],
    //             subMenu: [],
    //         },
    //     ],
    // },
    // {
    //     key: 'reservationManagement',
    //     path: '',
    //     title: 'Reservation',
    //     icon: 'Group collapse menu',
    //     translateKey: 'nav.orderManagement',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'menuDish.item1',
    //             path: '/reservations/:restaurantId/reservations',
    //             title: 'Reservation List',
    //             translateKey: 'reservationManagement.collapse.item1',
    //             icon: 'list',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },

    // {
    //     key: 'restaurantManagement',
    //     path: '',
    //     title: 'Restaurant Operations',
    //     translateKey: 'nav.restaurantOps',
    //     icon: 'restaurant',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [OWNER, ADMIN, STAFF],
    //     subMenu: [
    //         {
    //             key: 'orders',
    //             path: '/owner/dashboard', // Redirects to selector dashboard if no specific context active
    //             title: 'Orders Management',
    //             translateKey: 'nav.orders',
    //             icon: 'order',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [OWNER, ADMIN, STAFF],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'dishes',
    //             path: '/owner/dashboard',
    //             title: 'Menu Items / Dishes',
    //             translateKey: 'nav.dishes',
    //             icon: 'dish',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [OWNER, ADMIN, STAFF],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'reservations',
    //             path: '/owner/dashboard',
    //             title: 'Reservations',
    //             translateKey: 'nav.reservations',
    //             icon: 'calendar',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [OWNER, ADMIN, STAFF],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'staff',
    //             path: '/owner/dashboard',
    //             title: 'Staff Administration',
    //             translateKey: 'nav.staff',
    //             icon: 'users',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [OWNER, ADMIN],
    //             subMenu: [],
    //         },
    //     ],
    // },
    /** Example purpose only, please remove */
    // {
    //     key: 'singleMenuItem',
    //     path: '/single-menu-view',
    //     title: 'Single menu item',
    //     translateKey: 'nav.singleMenuItem',
    //     icon: 'singleMenu',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    // {
    //     key: 'collapseMenu',
    //     path: '',
    //     title: 'Restaurants',
    //     translateKey: 'nav.collapseMenu.collapseMenu',
    //     icon: 'collapseMenu',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'collapseMenu.item1',
    //             path: '/collapse-menu-item-view-1',
    //             title: 'Collapse menu item 1',
    //             translateKey: 'nav.collapseMenu.item1',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'collapseMenu.item2',
    //             path: '/collapse-menu-item-view-2',
    //             title: 'Collapse menu item 2',
    //             translateKey: 'nav.collapseMenu.item2',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },
    {
        key: 'ordersAndReservations',
        path: '',
        title: 'Orders & Reservations',
        translateKey: 'nav.groupMenu.groupMenu',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [OWNER, STAFF],
        subMenu: [
            {
                key: 'order.list',
                path: '/restaurants/:restaurantId/orders',
                title: 'Order List',
                translateKey: 'orderManagement.collapse.item1',
                icon: 'groupSingleMenu', //'list',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [OWNER, STAFF],
                subMenu: [],
            },
            {
                key: 'reservation.list',
                path: '/restaurants/:restaurantId/reservations',
                title: 'Reservation List',
                translateKey: 'reservationManagement.collapse.item1',
                icon: 'groupCollapseMenu', //'list',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    // {
    //     key: 'groupMenu',
    //     path: '',
    //     title: 'Group Menu',
    //     translateKey: 'nav.groupMenu.groupMenu',
    //     icon: 'groupMenu',
    //     type: NAV_ITEM_TYPE_TITLE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'groupMenu.single',
    //             path: '/group-single-menu-item-view',
    //             title: 'Group single menu item',
    //             translateKey: 'nav.groupMenu.single',
    //             icon: 'groupSingleMenu',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'groupMenu.collapse',
    //             path: '',
    //             title: 'Group collapse menu',
    //             translateKey: 'nav.groupMenu.collapse.collapse',
    //             icon: 'groupCollapseMenu',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [],
    //             subMenu: [
    //                 {
    //                     key: 'groupMenu.collapse.item1',
    //                     path: '/group-collapse-menu-item-view-1',
    //                     title: 'Menu item 1',
    //                     translateKey: 'nav.groupMenu.collapse.item1',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'groupMenu.collapse.item2',
    //                     path: '/group-collapse-menu-item-view-2',
    //                     title: 'Menu item 2',
    //                     translateKey: 'nav.groupMenu.collapse.item2',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //             ],
    //         },
    //     ],
    // },
]

export default navigationConfig

export const getDashboardOnlyNavigation = (): NavigationTree[] => [
    {
        key: 'owner.dashboard',
        path: '/owner/dashboard',
        title: 'Main Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [OWNER],
        subMenu: [],
    },
]
